### ISSUE TITLE
Documentation is a bit confusing

### ISSUE THREAD

**Issue by philippe56** [amir73il/linux#6]
The file overlayfs-snapshots.txt is difficult to read, because it uses the historical overlay mount vocabulary to describe both regular and snapshot overlay mounts.

I suggest that we introduce new adjectives to qualify the new snapshot overlay directories, for clarity, respectively substituting 'snapshot' to 'upper', and 'live' to 'lower'.

Hardly readable sentences like
    The 'upperdir=' mount option points to the lower dir of the snapshot overlay.
would be replaced by the straightforward
    The 'upperdir=' mount option points to the live dir of the snapshot overlay.

Here is a patch that fixes overlayfs-snapshots.txt along those lines:
[ovl_snapshots-documentation.patch.txt](https://github.com/amir73il/linux/files/1038111/ovl_snapshots-documentation.patch.txt)

**Comment by amir73il** [comment]
@philippe56 Thanks for the comment and for the patch.
I agree with you that "documentation is a bit confusing" and that the terminology should be revised for less ambiguity.
The change s/lower/live/ may be acceptable. I need to sleep on it.
The change s/upper/snapshot/ is not correct because it creates another ambiguity.

There is an important distinction between the "snapshot diff" which contains only the modified files and the "snapshot mount" which contains the entire snapshot view.

For example, this change in your patch is incorrect:
-  mount -t overlay snap3 -olowerdir=/upper/3:/snap/4 /snap/3
+  mount -t overlay snap3 -olowerdir=/snap/3:/snap/4 /snap/3
 
Because "snapshot mount" 3 is composed of "snapshot mount" 4 (latest) and "snapshot diff" 3
It could have been written as:
-  mount -t overlay snap3 -olowerdir=/diff/3:/snap/4 /snap/3

**Comment by philippe56** [comment]
Ouch. I missed this completely, to the point that I did not transpose at all your original sentence:

  "the historic upper layers are used as lower layers in reverse order, oldest upper layer on top."

I understand now that "historic" means snapshot-unmounted, with immutable snapshot delta data.

So, right, I will try to revisit my vocabulary, and propose a new patch if I find something suitable.

Thank you for clarifying.

**Comment by philippe56** [comment]
I have changed my mind. Changing vocabulary will not help.
I think that my initial feeling was due to my lack of overlayfs practice.
Closing the issue.

**Comment by amir73il** [comment]
Glad it works for you.
As a take away, I do think that you were right about this sentence being hard to digest:
The 'upperdir=' mount option points to the lower dir of the snapshot overlay.

I think the solution is to kill the upperdir= mount option for snapshot mount, i.e.:
<pre>
A snapshot mount command takes a source and target dir and one mandatory
mount option: 'snapshot='.  The 'snapshot=' mount option points to a snapshot
overlay mount point.  The lower dir of the snapshot overlay must be the source
dir of the snapshot mount. For example:

  mount -t snapshot /lower /mnt -o snapshot=/snap/0
</pre>
